ДЗ 1
webDevArtur/2024-2-VK-EDU-Frontend-A-Gaik pull request #1
Opened 2024-09-22 17:50 UTC by webDevArtur

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Реализована функция convertBytesToHuman и соответствующие тесты
* Реализована функция nonUniqueElements
* Реализована функция correctSentence

2024-09-24 17:42 UTC, Ivan-Bir requested changes

2024-09-24 17:42 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +/*
Привет! Добро пожаловать на курс
Я буду твоим ментором и буду рад ответить на любые вопросы по курсу

2024-09-24 17:42 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  return `${parseFloat(bytes.toFixed(2)).toString()} ${arr[index]}`;
Не обязательно приводить явно к строке, число и так находится внутри шаблонной строки

2024-09-24 17:42 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +});
В задании, мне кажется, работа должна идти с целыми числами, ведь обычно все данные хранятся в целых байтах, возможно коллеги меня поправят. Предлагаю обрабатывать так, чтобы convertBytesToHuman(0.1) -> 0 B. И добавить на это тест соответственно. Это необязательный пункт, потому что явно в задании про это не сказано, оставляю на твоё усмотрение

2024-09-24 17:42 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +test('Проверка на отрицательные числа', () => {
Избыточные проверки, достаточно одной в категории неверных входных данных

2024-09-24 17:42 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +test('Возвращает false для неправильного типа данных', () => {
Обычно сначала пишут позитивные кейсы. Так чуть проще читать код тестов

2024-09-24 17:42 UTC, Ivan-Bir commented on correctSentence.js
> +}
Не забываем про пустую строку в конце файла. Это помогает избегать лишних мерж конфликтов

2024-09-24 17:42 UTC, Ivan-Bir commented on correctSentence.test.js
> +test('returns correct sentence', () => {
Не покрыты пограничные случаи. Например пустая строка

2024-09-24 17:42 UTC, Ivan-Bir commented on correctSentence.js
> +    return firstLetter + text.slice(1) + lastLetter;
Шаблонные строки немного лучше таких конструкций. Если использовал в первой задаче, то почему передумал здесь?

2024-09-24 17:42 UTC, Ivan-Bir commented on correctSentence.js
> +    }
Если отрабатывает условие, то действие выше выполняется просто так

2024-09-24 17:42 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  return data.filter(num => elements[num] > 1);
А давай попробуем решить задачу за один обход массива + используя молодежные методы работы с массивами
Если не читал, то мастхев https://learn.javascript.ru/array-methods

2024-09-24 17:42 UTC, Ivan-Bir commented on nonUniqueElements.test.js
> +  expect(nonUniqueElements([10, 9, 10, 10, 9, 8])).toEqual([10, 9, 10, 10, 9]);
Добавил бы парочку кейсов от себя

2024-09-25 21:25 UTC, webDevArtur commented on convertBytesToHuman.js
> +  return `${parseFloat(bytes.toFixed(2)).toString()} ${arr[index]}`;
Спасибо, исправил

2024-09-25 21:26 UTC, webDevArtur commented on convertBytesToHuman.test.js
> +});
Написал тест, но решил всё-таки данный кейс свести к convertBytesToHuman(0.1) -> false

2024-09-25 21:27 UTC, webDevArtur commented on convertBytesToHuman.test.js
> +test('Проверка на отрицательные числа', () => {
Исправил

2024-09-25 21:27 UTC, webDevArtur commented on convertBytesToHuman.test.js
> +test('Возвращает false для неправильного типа данных', () => {
Спасибо, поправил

2024-09-25 21:28 UTC, webDevArtur commented on correctSentence.test.js
> +test('returns correct sentence', () => {
Возможно я что-то не понял, но судя по заданию, доработки требовал только один test из трёх, но на всякий случай, постарался поправить, согласно замечанию
![Снимок экрана 2024-09-26 002744](https://github.com/user-attachments/assets/201d3a7a-dca8-4215-9a43-a0a776f09e69)

2024-09-25 21:29 UTC, webDevArtur commented on nonUniqueElements.test.js
> +  expect(nonUniqueElements([10, 9, 10, 10, 9, 8])).toEqual([10, 9, 10, 10, 9]);
Возможно я что-то не понял, но судя по заданию, доработки требовал только один test из трёх, но на всякий случай, постарался поправить, согласно замечанию
![Снимок экрана 2024-09-26 002744](https://github.com/user-attachments/assets/201d3a7a-dca8-4215-9a43-a0a776f09e69)

2024-09-25 21:33 UTC, webDevArtur commented on nonUniqueElements.js
> +  return data.filter(num => elements[num] > 1);
К сожалению, очень долго искал варианты, не придумал как это сделать в один обход массива, исключая случаи с Set, где, как я понимаю под капотом будет так же проход осуществляться, ничего не придумал.

Если сможете написать вариант фильтрации всех неуникальных значений за один обход массива, то буду очень благодарен и постараюсь разобраться.

2024-09-25 21:35 UTC, webDevArtur commented on correctSentence.js
> +    }
Тут задумка в том, что  '     ' - строка состоящая из пробелов, должна тоже быть исключен, по моему мнению, поэтому я первым делом всё равно убираю пробелы, поправьте меня пожалуйста, если я не прав

2024-09-25 21:35 UTC, webDevArtur commented on correctSentence.js
> +    return firstLetter + text.slice(1) + lastLetter;
Спасибо большое, буду иметь ввиду, исправил

2024-09-26 14:21 UTC, Ivan-Bir commented on correctSentence.test.js
> +test('returns correct sentence', () => {
Приучаемся, что если видим, то что мы можем поправить на месте, то правим

2024-09-26 14:21 UTC, Ivan-Bir commented on correctSentence.js
> +    }
Окей, убедил

2024-09-26 14:23 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +test('Возвращает false для неправильного типа данных', () => {
Если комент исправляешь как сказано в замечании, то после исправления можешь закрывать тред. Оставляй открытыми для дискуссий. На будущее

2024-09-26 14:25 UTC, Ivan-Bir commented on nonUniqueElements.test.js
> +  expect(nonUniqueElements([10, 9, 10, 10, 9, 8])).toEqual([10, 9, 10, 10, 9]);
Писал выше. Смотря в кейсы приучаемся думать о граничных случаях даже для готовых функций или тестов. Если не заметил предыдущий разработчик, то можешь заметить ты

2024-09-26 14:29 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +});
Не забываем добавлять пустую строчку в конце каждого файла

2024-09-26 14:39 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  return data.filter(num => elements[num] > 1);
Не обратил внимание на то, что порядок должен остаться прежним. Хорошее решение, вопросов нет

2024-09-26 14:40 UTC, Ivan-Bir approved these changes, later dismissed

2024-09-26 14:40 UTC, Ivan-Bir commented
Есть совсем незначительные замечания. Апрув ставлю

2024-09-29 13:43 UTC, martinkomitsky commented on pull_request_template.md
> +Прошу @martinkomitsky, @haseprogram, @kgrechin или @ваш_назначенный_ментор проверить его.
```suggestion
Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

```

2024-09-29 13:44 UTC, martinkomitsky approved these changes
12!

2024-09-29 13:44 UTC, merged