ДЗ 4
webDevArtur/2024-2-VK-EDU-Frontend-A-Gaik pull request #10
Opened 2024-10-09 23:42 UTC by webDevArtur

# Домашнее задание №4

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Добавлена логика поиска по контактам

![image](https://github.com/user-attachments/assets/5aa7749f-412c-4ee2-bce2-07d3818d4890)

* Добавлена логика добавления контактов

![image](https://github.com/user-attachments/assets/2cc05b7e-6c17-415d-aaa5-3d78df7e7cac)

* Добавлены визуальные эффекты при наведении, анимация появления сообщений, был запрещен пользовательский зум

2024-10-10 09:08 UTC, Ivan-Bir commented
Добавь ссылочку на деплой

2024-10-12 20:19 UTC, Ivan-Bir requested changes
По коду незначительные комментарии.
По продукту есть что доработать.
В форме добавления нового чата есть поле url аватарки. Это совсем не юзер-френдли. А если не указать, то покажется битая картинка :(
Как можно обыграть: Всем изначально ставить какую-то дефолтную картинку, но дать возможность менять её для конкретного юзера. В идеале выбрать файл с устройства

2024-10-12 20:19 UTC, Ivan-Bir commented on simple-chat/components/Modal/Modal.css
> +
Насчет пустых строк и prettier. Нужно покопаться в его настройках
https://www.digitalocean.com/community/tutorials/how-to-format-code-with-prettier-in-visual-studio-code-ru

2024-10-12 20:19 UTC, Ivan-Bir commented on simple-chat/components/FloatingActionButton/FloatingActionButton.js
> +  button.innerHTML = `<i class="material-icons">mode_edit</i>`;
Что мешает также использовать insertAdjacentHTML?

2024-10-12 20:19 UTC, Ivan-Bir commented on simple-chat/js/chats.js
> +  chatListContainer.innerHTML = chatItemsHtml;
Это зря

2024-10-12 20:19 UTC, Ivan-Bir commented on simple-chat/components/Modal/Modal.js
> +export function Modal() {
Это скорее AddChatModal, а не тот Modal, в который можно передать любой другой компонент и он будет вести себя как модалка, например, с крестиком, обработчиком закрытия по внешней области и тд. Советую так сделать

2024-10-14 19:10 UTC, Ivan-Bir approved these changes
Отлично
Можно ещё что-то придумать, чтобы новые чаты сохранялись при перезагрузке

2024-10-14 19:10 UTC, Ivan-Bir commented on convertBytesToHuman.js
>   */
Давай уберем следы первого дз из репы

2024-10-14 19:10 UTC, Ivan-Bir commented on simple-chat/components/addChatModal/addChatModal.js
> +    title: 'Добавить новый контакт',
Лучше смотрится, когда эта надпись в одну линию с крестиком

2024-10-14 19:10 UTC, Ivan-Bir commented on simple-chat/components/addChatModal/addChatModal.js
> +      <button class="modal-button" type="submit">Добавить</button>
Дефолтная кнопка так и просит, чтобы её стилизовали

2024-10-19 12:18 UTC, merged

2024-10-19 12:18 UTC, martinkomitsky commented
12!