ДЗ 5
webDevArtur/2024-2-VK-EDU-Frontend-A-Gaik pull request #11
Opened 2024-10-24 01:10 UTC by webDevArtur

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:

- Ссылка на деплой: https://webdevartur.github.io/2024-2-VK-EDU-Frontend-A-Gaik/
- Чаты сохраняются при перезагрузке страницы
- Убрал следы первого ДЗ из репозитория
- Надпись и крестик в модальном окне расположил в одну строку

![image](https://github.com/user-attachments/assets/4f0fce29-9620-4290-90c4-c2b97c9681d8)

- Дефолтная кнопка загрузки изображения была стилизована
- Был создан новый проект с использованием **npm create vite@latest react-chat**
- Иконки были переписаны с использованием MUI
- Были восстановлены все стили компонентов  при переходе на react (сохранена адаптивность)
- Была восстановлена функциональность при переходе на react
- Переход между страницами реализован с использованием react state, согласно заданию
- Был восстановлен деплой проекта с учетом изменения репозитория

2024-10-24 15:10 UTC, Ivan-Bir requested changes
Переезд выполнен хорошо в целом. Есть небольшие комментарии по коду

Не заметил ощутимой продуктовой разницы, поэтому подсвечу некоторые моменты в UI:
1) Не понятно с кем в данный момент открыт чат
2) Хочется уметь возвращаться назад ещё через стрелочки браузера. Это делается через работу с historyAPI и потребует научить приложенько заходить в чат по прямому урлу
3) Нет поиска по сообщениям
4) Нет возможности обновить фото контакта

2024-10-24 15:10 UTC, Ivan-Bir commented on README.md
> +- [@vitejs/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) uses [SWC](https://swc.rs/) for Fast Refresh
Поправь описание репы

2024-10-24 15:10 UTC, Ivan-Bir commented on src/App.jsx
> +        return null;
Лучше оставлять заглушку в стиле "сорян, такую страницу не нашли"

2024-10-24 15:10 UTC, Ivan-Bir commented on src/App.jsx
> +      />
Чтобы хедер не перерендеривался на каждую смену страницы лишний раз, можно заюзать React.memo

2024-10-24 15:10 UTC, Ivan-Bir commented on src/components/ChatItem/ChatItem.jsx
> +          <span className={styles.badge}>{unreadCount}</span>
Сейчас не сбрасывается счетчик непрочитанных

2024-10-24 15:10 UTC, Ivan-Bir commented on src/hooks/Storage.js
> +export function saveMessageToLocalStorage(message, chatId) {
это не hook, а helper скорее

2024-10-29 16:59 UTC, Ivan-Bir approved these changes
Продукт приближается к своему MVP, так держать

Есть несколько моментов в UI:
1. Отступы по краям шапки должны быть выровнены с основным контентом. Сейчас проглядывается лесенка
2. Шапка с активным юзером в чате как-то оторвана. Предлагаю как-то её совместить с хедером, уменьшить шрифт, добавить контекстное меню (Лучше перенести логику обновления фото внутрь чата). Постарайся не оставлять так много пустого места в блоке
3. В общем списке не отображаются последние сообщения
4. Давай лого сделаем кликабельным, будет вести на список чатов, это частый паттерн
5. Маленький баг с тем, что если обновлять страницу /profile, то сначала подтягивается дефолтное значение, потом только актуальное
6. Хотелось бы больше возможностей для непосредственного общения. Как смотришь на то, чтобы добавить селектор с эмодзи и аттачи с картинками (или даже с файлами). Можно подумать в сторону форматирования, будешь выгодно отличаться от самого VK Мессенджера)

Можешь поправить уже в след дз, пингани тогда меня в тг, посмотрю дз6

2024-10-29 16:59 UTC, Ivan-Bir commented on src/pages/PageChat/PageChat.jsx
> +    setFriendName(chat ? chat.title : "Неизвестный собеседник");
Это вводит в заблуждение. С ним же нельзя общаться. Лучше показать 404 "Не нашли такого пользователя"

2024-10-31 06:44 UTC, HaseProgram approved these changes
12! Не забывайте указывать ревьюверов и ассайнить пр на преподавателя - можем пропустить нечаяно

2024-10-31 06:44 UTC, merged