ДЗ 6
webDevArtur/2024-2-VK-EDU-Frontend-A-Gaik pull request #12
Opened 2024-10-28 21:44 UTC by webDevArtur

# Домашнее задание №6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:

- Ссылка на деплой https://webdevartur.github.io/2024-2-VK-EDU-Frontend-A-Gaik/
- Был подключен react-router
- Настроена клиентская маршрутизация для своих страниц
- Конкретный чат должен по ссылке (например, /chat/1, /chat/2 и т.д.)
- Использован HashRouter, чтобы на GitHub Pages всё работало корректно
- Добавлена страница профиля

![image](https://github.com/user-attachments/assets/9dc911d5-2d96-49c7-9026-77df4a403077)

2024-10-30 11:24 UTC, Ivan-Bir requested changes
Нужны небольшие доработки.

Всё-таки давай выровняем верстку, например по краям нижней панели с текстовым инпутом. Обрати внимание как отступы сделаны в телеграме например. Это касается не только чата, но и шапки, и списка чатов

2024-10-30 11:24 UTC, Ivan-Bir commented on src/pages/PageChat/PageChat.jsx
> +      image: imageAttachment ? URL.createObjectURL(imageAttachment) : null,
При обновлении страницы картинки перестают грузиться. Пусть так не делают, то лучше будет работать в base64, чем никак

2024-10-30 11:24 UTC, Ivan-Bir commented on src/pages/PageChat/PageChat.jsx
> +      image: imageAttachment ? URL.createObjectURL(imageAttachment) : null,
Кстати заодно неплохо думать, как может развиваться эта фича дальше. Сейчас ты указал поле image, а потенциально картинок можно много отправлять. Дальше тогда придется рефачить это поле, делать его массивом, и скорее всего без костылей обратная совместимость оторвется. Это на подумать

Можно сразу сделать поле массивом, и обрабатывать только первый элемент, а потом останется доработать обработчик и приложение без болей научится отправлять сразу несколько картинок.

2024-10-31 15:07 UTC, Ivan-Bir approved these changes, later dismissed

2024-10-31 15:08 UTC, Ivan-Bir commented
Предлагаю дальше подумать над группировкой сообщений, если они идут друг за другом. Сейчас достаточно большие отступы между сообщениями.
Аппрув ставлю

2024-10-31 15:08 UTC, Ivan-Bir approved these changes

2024-10-31 15:09 UTC, Ivan-Bir submitted a review, later dismissed

2024-10-31 15:17 UTC, Ivan-Bir approved these changes, later dismissed

2024-10-31 15:19 UTC, Ivan-Bir submitted a review, later dismissed
.

2024-10-31 22:02 UTC, closed without merging

2024-11-05 09:12 UTC, martinkomitsky commented
12