Домашнее задание №7
webDevArtur/2024-2-VK-EDU-Frontend-A-Gaik pull request #14
Opened 2024-11-24 07:09 UTC by webDevArtur

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:

- Получение и отправка всех данных была переписана с использованием backend

2024-11-24 15:41 UTC, Ivan-Bir requested changes
Привет. Добавь плиз ссылочку на деплой, чтобы не искать. 
Не удалось зарегистрироваться. Вижу, просто нет запроса на регу. Смотрю в firefox. Если входить несуществующим акком, то пишет нечеловекопонятную ошибку "не удалось выйти из системы".
Так же несколько моментов по UI:
1) Для потенциально опасных действий, как удаление чего-то, или смена пароля, уже стандартом является показывать предупреждающее окошко, в котором надо подтвердить свои намерения. Иначе возможны случайны клики по корзинке, которая тем более не спрятана за какой-то менюшкой
2) Картинки в сообщениях не отображаются
3) Не отправляются сообщения
![изображение](https://github.com/user-attachments/assets/5336fc04-4945-4d02-9223-1d9e5aed6be6)
4) Строка ввода сообщения уехала вверх
5) Клик на лого не возвращает на список чатов

2024-11-24 15:41 UTC, Ivan-Bir commented on src/hooks/useCentrifugo.jsx
> +          if (!centrifuge.isConnected()) {
Не нашел isConnected в доке, есть только _isConnected, но него смотреть не рекомендуется, потому что это приватное поле. Думаю повторную попытку подключения для этого случая надо убрать под событие 'error'.

2024-11-24 15:41 UTC, Ivan-Bir commented on src/pages/LoginPage/LoginPage.jsx
> +          Нет аккаунта?{' '}
Что-то лишнее, на .switchLink уже висит margin-left

2024-12-06 07:21 UTC, Ivan-Bir commented
Привет! Когда ожидаем тут правок?

2024-12-21 13:34 UTC, Ivan-Bir approved these changes

2024-12-22 09:37 UTC, merged

2024-12-22 09:37 UTC, martinkomitsky commented
7