Домашнее задание №8
webDevArtur/2024-2-VK-EDU-Frontend-A-Gaik pull request #15
Opened 2024-12-20 16:57 UTC by webDevArtur

# Домашнее задание №8

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:

- Реализовал запись и отправку голосовых сообщений.
- Реализовать отправку картинок
- Реализовать отправку координат пользователя

2024-12-21 14:16 UTC, Ivan-Bir requested changes, later dismissed
Привет!
Заметил ошибку при попытке отправить текст вместе с голосовым. Чтобы такого избежать можно блокировать инпут ввода и другие аттачи. + Показывать анимацию, что идет запись
Хотелось бы при отправке геопозиции получать не ссылку, а вставлять виджет карты, где видно мою точку. Ничего сложного, просто открывать айфрейм какого-то сервиса карт с нужными координатами.
По коду вопросов нет

Предлагаю ещё здесь же поддержать удаление или редактирование сообщения

2025-01-12 14:12 UTC, Ivan-Bir commented
Привет! Ожидать здесь правок? Если да, то нужно обновить деплой

2025-01-17 10:05 UTC, martinkomitsky submitted a review, later dismissed
поставил 7 без ревью. Дальше уже времени нет оценку повышать

2025-01-17 10:06 UTC, martinkomitsky approved these changes

2025-01-17 10:06 UTC, merged