ДЗ 2
webDevArtur/2024-2-VK-EDU-Frontend-A-Gaik pull request #8
Opened 2024-09-30 21:53 UTC by webDevArtur

# Домашнее задание № 2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Ссылка на деплой: https://webdevartur.github.io/2024-2-VK-EDU-Frontend-A-Gaik
* На основе директории simple-chat написана страница чата
* Добавлены css стили, элементы расположены с помощью css flexbox, страница адаптивна
На мобильном устройстве:
![image](https://github.com/user-attachments/assets/b0af107c-55c3-40a2-8064-1b4f2976a268)
На компьютере:
![image](https://github.com/user-attachments/assets/1c01208e-9bd6-4c78-81bf-a809cbd442ab)
Отображение пустого списка сообщений:
![image](https://github.com/user-attachments/assets/4b93832d-ef08-41ed-a197-f260cb82d491)

* Добавлены иконки material icons
* Все сообщения введенные пользователем сохраняются в localStorage
* После отправки сообщения поле ввода очищается

2024-10-01 19:46 UTC, Ivan-Bir commented
Привет! Хорошая работа
Есть несколько продуктовых моментов для улучшения
1) Когда отравляем по Enter, то страница перезагружается - признак того, что не так сабмитится форма
2) После отправки хорошо бы ставить на инпут focus, чтобы сразу можно было начинать набирать новое сообщение

2024-10-01 20:15 UTC, Ivan-Bir requested changes
Есть некритичные моменты на доработки

2024-10-01 20:15 UTC, Ivan-Bir commented on simple-chat/src/index.css
> +.chatTitle i {
В сложных селекторах проще ошибиться, и они менее гибкие для дальнейших изменений. Почти в 100% случаев можно обойтись понятным именем класса

2024-10-01 20:15 UTC, Ivan-Bir commented on simple-chat/src/index.css
> +input {
Стилизовать теги вариант не очень. А что если где-то в другом месте тебе понадобится input другого вида? Для элементов удобнее и практичнее использовать классы
Но стили для тегов тоже пишут, например когда нужно сбросить стандартные стили браузера, например на теге body, или a

2024-10-01 20:15 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +    if (messageText === '') return;
Продолжаю настойчиво напоминать про однострочные ифаки

2024-10-01 20:15 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +    event.preventDefault();
Расскажешь, для чего эта конструкция?
Надеюсь на развернутый ответ

2024-10-01 20:15 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +}
Неоптимально по ресурсам. На каждое добавление ты парсишь все сообщения, и потом обратно всё это в json. 95% данных конвертируются туда-сюда без надобности. Пожалей пользователей со слабыми телефонами: они или умрут от ожидания отправки сообщения, или сожгут себе руки из-за перегрева проца.
Давай придумаем какой-то ещё способ хранения сообщений

2024-10-01 20:15 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +    if (messages.length === 0) {
Эту конструкцию будет проще воспринимать, если пойти от негативного условия:
 if (messages.length !== 0) {
         messages.forEach(addMessageToDOM);
         return;
}
// весь остальной код без else

2024-10-01 20:15 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +        form.dispatchEvent(new Event('submit'));
Лучше не выбрасывать события вручную. Можно вызывать handleSubmit напрямую

2024-10-01 23:09 UTC, webDevArtur commented on simple-chat/src/index.js
> +    event.preventDefault();
Это помогает избежать дефолтного(стандартного) поведения браузера при вызове события отправки формы, она по умолчанию считывает данные с полей формы, отправляет их на какой-то url и обновляет страницу, а так как мы пишем свой функционал на отправку формы, то нам необходимо отключить эти стандартные поведения.

2024-10-01 23:49 UTC, webDevArtur commented on simple-chat/src/index.js
> +}
Попробовал решить через отдельные сообщения, это привело к нарушению порядка сообщений при обновлении страницы, другого ничего не смог придумать с localStorage, поэтому решил вернуть первый вариант.
![image](https://github.com/user-attachments/assets/fca1b01a-2f3f-4dca-a981-efcb3f8c5728)

2024-10-02 12:24 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +    event.preventDefault();
На погрузиться глубже:
https://learn.javascript.ru/introduction-browser-events
https://learn.javascript.ru/bubbling-and-capturing
https://learn.javascript.ru/default-browser-action

2024-10-02 12:26 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +}
Как вариант - проставлять порядковые номера сообщениям в ключах, и хранить общее число сообщений

2024-10-03 15:01 UTC, Ivan-Bir approved these changes

2024-10-03 15:01 UTC, Ivan-Bir commented
Критичного ничего не нашел. Апрув

2024-10-03 18:06 UTC, HaseProgram approved these changes
12!

2024-10-03 18:07 UTC, merged