ДЗ 3
webDevArtur/2024-2-VK-EDU-Frontend-A-Gaik pull request #9
Opened 2024-10-05 18:53 UTC by webDevArtur

# Домашнее задание № 3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Ссылка на деплой: https://webdevartur.github.io/2024-2-VK-EDU-Frontend-A-Gaik
* Добавлена новая страница 

На компьютере:

![image](https://github.com/user-attachments/assets/6a2aef97-6b18-40fb-8d7f-bbe7d1a9e480)

На мобильном устройстве: 
![image](https://github.com/user-attachments/assets/40cd3ad9-3e75-48c3-966e-359545beec38)

*  Страница была декомпозирована на отдельные компоненты, js и css файлы
*  Был предусмотрен переход на страницу выполненную в предыдущем задании
*  Были использованы современные возможности js, такие как шаблонные строки, стрелочные функции, параметры по умолчанию, деструктуризация объектов ...

2024-10-06 15:36 UTC, Ivan-Bir requested changes
Нужны доработки

2024-10-06 15:36 UTC, Ivan-Bir commented on simple-chat/chat.html
> +<!doctype html>
Привет!
Как я понимаю суть курса - это научить вас писать хорошие SPA. Поэтому давай уйдем от множественных html, и оставим только index.html для подгрузки скриптов (да, список чатов тоже в отдельный компонент). Не вижу проблем вынести статичную верстку по аналогии как это уже сделано.
Что это даст? Возможность переключаться между страницами без перезагрузки вкладки. Разделение на компоненты, которое подразумевается в дз. Это будет и быстрее и плавнее

Чтобы правильно поддержать переходы по стрелочке "Назад" для SPA, то можно почитать про апи браузерной истории
https://developer.mozilla.org/en-US/docs/Web/API/History/pushState

2024-10-06 15:36 UTC, Ivan-Bir commented on simple-chat/js/index.js
> +  ]
Давай тестовые данные вынесем в отдельное место, например \_\_mocks\_\_.js

2024-10-09 11:27 UTC, Ivan-Bir commented on simple-chat/components/ChatItem/ChatItem.css
> +  cursor: pointer;
Если кнопка на самом деле не работает, но визуально намекает её нажимать, то это моветон

2024-10-09 11:31 UTC, Ivan-Bir commented on simple-chat/public/mocks.js
> +      message: 'Ты куда пропал?',
И хорошо было, чтобы если на превью это сообщение, то показывать его в диалоге с человеком. А то выглядит как баг

2024-10-09 11:31 UTC, Ivan-Bir approved these changes

2024-10-09 11:34 UTC, Ivan-Bir commented
Критичных замечаний нет.
Предлагаю в следующем дз доделать функцию поиска и создания чата с новым человеком

2024-10-09 18:23 UTC, merged

2024-10-09 18:23 UTC, martinkomitsky commented
12!